language: cpp

script:
  - git clone --depth=50 --branch=develop git://github.com/zussel/oos.git zussel/oos
  - cd zussel/oos
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - make test

branches:
  only:
    - develop
