version: 0.2.1.{build}

services:
  - mssql2008r2sp2
  - mysql

configuration:
- Debug
- Release

environment:
  matrix:
#  - VS_VERSION: 11
#    VS_PLATFORM: win32
#  - VS_VERSION: 11
#    VS_PLATFORM: x64
#  - VS_VERSION: 12 2013
#    VS_PLATFORM: win32
#  - VS_VERSION: 12 2013
#    VS_PLATFORM: x64
  - VS_VERSION: 14 2015
    VS_PLATFORM: win32
  - VS_VERSION: 14 2015
    VS_PLATFORM: x64

#install:
#  - cinst: nsis

before_build:
- mkdir build
- cd build
#- cmake -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -DOOS_ODBC=false -DOOS_SQLITE3=false -DOOS_MYSQL=false ..
- cmake -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -DOOS_ODBC=true -DMSSQL_CONNECTION_STRING:STRING="mssql://sa:Password12!@127.0.0.1/SQL2008R2SP2/oos_test" -DOOS_SQLITE3=false -DOOS_MYSQL=false -DMYSQL_CONNECTION_STRING:STRING="mysql://root:Password12!@127.0.0.1/oos_test" ..
#- set MYSQL_PWD=Password12!
#- set USER=root
#- mysql -e "create database oos_test;" --user=root
- sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE oos_test"

build:
  project: C:\projects\oos\build\oos.sln

test_script:
- cd C:\projects\oos\build && if %CONFIGURATION%==Debug (ctest --verbose -E perftest --build-config %CONFIGURATION%) else (ctest --verbose --build-config %CONFIGURATION%)
