version: 0.2.1.{build}

configuration:
- Debug
- Release

environment:
  matrix:
#  - VS_VERSION: 11
#    VS_PLATFORM: win32
#  - VS_VERSION: 11
#    VS_PLATFORM: x64
  - VS_VERSION: 12
    VS_PLATFORM: win32
  - VS_VERSION: 12
    VS_PLATFORM: x64

before_build:
- mkdir build
- cd build
- cmake -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -DOOS_ODBC=false -DOOS_SQLITE3=false -DOOS_MYSQL=false ..

build:
  project: C:\projects\oos\build\oos.sln

test_script:
- cd build && if %CONFIGURATION%==Debug (ctest --verbose -E perftest --build-config %CONFIGURATION%) else (ctest --verbose --build-config %CONFIGURATION%)
